// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'widget_header': string;
  'widget_header_bg': string;
  'widget_header_bg_bg1': string;
  'widget_header_bg_bg2': string;
  'widget_header_bg_bg3': string;
  'widget_header_content': string;
  'widget_header_display__none': string;
  'widget_header_fg': string;
  'widget_header_link': string;
  'widget_header_link__enabled': string;
  'widget_header_links': string;
  'widget_header_links_menu': string;
  'widget_header_links_menu__button': string;
  'widget_header_logo': string;
  'widget_header_logo_a': string;
  'widget_header_logo_img': string;
  'widget_header_logo_title': string;
  'widget_header_menu': string;
  'widget_header_modal': string;
  'widget_header_sitemenu': string;
  'widget_header_sitemenu__content': string;
  'widget_header_sitemenu__ignore': string;
  'widget_header_sitemenu_box_shadow': string;
  'widget_header_sitemenu_closed__content': string;
  'widget_header_sitemenu_fieldset': string;
  'widget_header_sitemenu_fieldset_legend': string;
  'widget_header_sitemenu_open__content': string;
  'widget_header_submenu_languages': string;
  'widget_header_submenu_link': string;
  'widget_header_submenu_links': string;
  'widget_header_submenu_themes': string;
  'widget_header_subtitle__div': string;
  'widget_header_title': string;
  'widget_header_title__div': string;
  'widget_header_title_subtitle': string;
  'widget_header_title_title': string;
  'widget_header_transition': string;
  'widget_header_transition__none': string;
  'widget_header_visibility__hidden': string;
}
export const cssExports: CssExports;
export default cssExports;
