// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'esri_input': string;
  'widget_support': string;
  'widget_support_buttons': string;
  'widget_support_buttons__disabled': string;
  'widget_support_buttons__div': string;
  'widget_support_buttons_cancel__div': string;
  'widget_support_buttons_submit__div': string;
  'widget_support_content': string;
  'widget_support_display__block': string;
  'widget_support_display__table': string;
  'widget_support_display__table_cell': string;
  'widget_support_display__table_row': string;
  'widget_support_form__div': string;
  'widget_support_form__label': string;
  'widget_support_form_input__error': string;
  'widget_support_form_message__div': string;
  'widget_support_form_name__div': string;
  'widget_support_form_textarea': string;
  'widget_support_form_textarea__label': string;
  'widget_support_header': string;
  'widget_support_header__div': string;
  'widget_support_header_close__button': string;
  'widget_support_header_close__div': string;
  'widget_support_header_heading__div': string;
  'widget_support_modal': string;
  'widget_support_visible__none': string;
}
export const cssExports: CssExports;
export default cssExports;
