// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'widget_cookies_all': string;
  'widget_cookies_all_buttons__disabled': string;
  'widget_cookies_all_content_message__div': string;
  'widget_cookies_all_header': string;
  'widget_cookies_all_header__div': string;
  'widget_cookies_all_header_close__button': string;
  'widget_cookies_all_header_close__div': string;
  'widget_cookies_all_header_heading__div': string;
  'widget_cookies_all_links__button': string;
  'widget_cookies_all_switch__container': string;
  'widget_cookies_all_switch__holder': string;
  'widget_cookies_all_switch__label': string;
  'widget_cookies_all_switch__toggle': string;
  'widget_cookies_all_transition': string;
  'widget_cookies_all_visible__none': string;
  'widget_cookies_main_buttons__div': string;
  'widget_cookies_main_buttons_accept__button': string;
  'widget_cookies_main_content': string;
  'widget_cookies_main_content__bottom': string;
  'widget_cookies_main_content__top': string;
  'widget_cookies_main_modal': string;
  'widget_cookies_main_subcontent__div': string;
  'widget_cookies_settings_buttons': string;
  'widget_cookies_settings_buttons__div': string;
  'widget_cookies_settings_buttons_accept__div': string;
  'widget_cookies_settings_buttons_reject__div': string;
  'widget_cookies_settings_buttons_save__div': string;
  'widget_cookies_settings_content': string;
  'widget_cookies_settings_content__div': string;
  'widget_cookies_settings_content_privacy__div': string;
  'widget_cookies_settings_modal': string;
  'widget_cookies_settings_subcontent': string;
  'widget_cookies_settings_subcontent__div': string;
  'widget_cookies_settings_subcontent_contact__div': string;
  'widget_cookies_settings_subcontent_title': string;
}
export const cssExports: CssExports;
export default cssExports;
