// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'widget_widgetbar': string;
  'widget_widgetbar_bg': string;
  'widget_widgetbar_bg__bg1': string;
  'widget_widgetbar_bg__bg2': string;
  'widget_widgetbar_bg__header': string;
  'widget_widgetbar_box_shadow': string;
  'widget_widgetbar_content': string;
  'widget_widgetbar_fg': string;
  'widget_widgetbar_fg__container': string;
  'widget_widgetbar_transition': string;
  'widget_widgetbar_visible__none': string;
  'widget_widgetbar_widget': string;
  'widget_widgetbar_widget__basemapgallery_controls_content': string;
  'widget_widgetbar_widget__bookmarks_controls_content': string;
  'widget_widgetbar_widget__layers_controls_content': string;
  'widget_widgetbar_widget__legend_controls_content': string;
  'widget_widgetbar_widget__print_controls_content': string;
  'widget_widgetbar_widget__sketch_controls_content': string;
}
export const cssExports: CssExports;
export default cssExports;
