// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'widget_extentnavigator': string;
  'widget_extentnavigator_content_horizontal': string;
  'widget_extentnavigator_content_vertical': string;
  'widget_extentnavigator_next_extent__button': string;
  'widget_extentnavigator_previous_extent__button': string;
}
export const cssExports: CssExports;
export default cssExports;
