// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'is-active': string;
  'load': string;
  'loader': string;
  'loader-bars': string;
  'loader-text': string;
  'modal-background': string;
  'padding-leader-3': string;
  'padding-trailer-3': string;
}
export const cssExports: CssExports;
export default cssExports;
