// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'widget_addlayer': string;
  'widget_addlayer__error': string;
  'widget_addlayer_buttontitle__label': string;
  'widget_addlayer_file__button': string;
  'widget_addlayer_file_button__div': string;
  'widget_addlayer_file_fileinfo__div': string;
  'widget_addlayer_file_uploadstatus__div': string;
  'widget_addlayer_file_uploadstatus__p': string;
  'widget_addlayer_file_uploadstatus_clear__button': string;
  'widget_addlayer_file_uploadstatus_clear_button__div': string;
  'widget_addlayer_p': string;
  'widget_addlayer_results__button': string;
  'widget_addlayer_results__div': string;
  'widget_addlayer_results_button__div': string;
  'widget_addlayer_results_button_wrapper__div': string;
  'widget_addlayer_results_layer__div': string;
  'widget_addlayer_results_layer__label': string;
  'widget_addlayer_service__div': string;
  'widget_addlayer_service__input': string;
  'widget_addlayer_service_button__div': string;
  'widget_addlayer_service_go__button': string;
  'widget_addlayer_service_input__div': string;
  'widget_addlayer_service_serviceInfo__div': string;
  'widget_addlayer_tab__button': string;
  'widget_addlayer_tab__div': string;
  'widget_addlayer_tabcontent__div': string;
  'widget_addlayer_visible__none': string;
}
export const cssExports: CssExports;
export default cssExports;
