// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'widget_footer': string;
  'widget_footer_bg': string;
  'widget_footer_bg_bg1': string;
  'widget_footer_bg_bg1a': string;
  'widget_footer_bg_bg2': string;
  'widget_footer_bg_bg2a': string;
  'widget_footer_bg_bg3': string;
  'widget_footer_bg_bg3a': string;
  'widget_footer_bg_bg4': string;
  'widget_footer_bg_bg4a': string;
  'widget_footer_bodytext': string;
  'widget_footer_bodytext_contact__anchor': string;
  'widget_footer_box_shadow': string;
  'widget_footer_button': string;
  'widget_footer_button_bar': string;
  'widget_footer_content': string;
  'widget_footer_copyright': string;
  'widget_footer_copyright__anchor': string;
  'widget_footer_fg': string;
  'widget_footer_links': string;
  'widget_footer_links__anchor': string;
  'widget_footer_links__linediv': string;
  'widget_footer_links__linkdiv': string;
  'widget_footer_modal': string;
  'widget_footer_subtitle__div': string;
  'widget_footer_title': string;
  'widget_footer_title__div': string;
  'widget_footer_transform_180': string;
  'widget_footer_transform_90_down': string;
  'widget_footer_transform_90_up': string;
  'widget_footer_transition': string;
  'widget_footer_transition__none': string;
  'widget_footer_visible__hidden': string;
  'widget_footer_visible__none': string;
}
export const cssExports: CssExports;
export default cssExports;
