// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'widget_map': string;
  'widget_map_content': string;
  'widget_map_transition': string;
  'widget_map_visible__none': string;
}
export const cssExports: CssExports;
export default cssExports;
