// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'widget_loading': string;
  'widget_loading_content': string;
  'widget_loading_img': string;
  'widget_loading_img__div': string;
  'widget_loading_visible__none': string;
}
export const cssExports: CssExports;
export default cssExports;
