// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'widget_disclaimer': string;
  'widget_disclaimer_button__disabled': string;
  'widget_disclaimer_button__div': string;
  'widget_disclaimer_checkbox': string;
  'widget_disclaimer_checkbox__div': string;
  'widget_disclaimer_checkbox__label': string;
  'widget_disclaimer_content': string;
  'widget_disclaimer_message__div': string;
  'widget_disclaimer_modal': string;
  'widget_disclaimer_title__div': string;
  'widget_disclaimer_visible__none': string;
}
export const cssExports: CssExports;
export default cssExports;
